apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
type: Opaque
stringData:  # Must be lowercase 's'
  # Since we are using stringData, NO base64 encoding is needed here!
  PORT: "3000"
  MONGO_URI: mongodb://12.10.1.222:27017/kubernetes