apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: default
type: Opaque
stringData:  # Must be lowercase 's'
  # Since we are using stringData, NO base64 encoding is needed here!
  VITE_API_BASE_URL: "http://12.10.1.222:3000/api"